export const ADD_IMAGE = 'ADD_IMAGE';
export const REMOVE_IMAGE = 'REMOVE_IMAGE';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const UPDATE_DETAILS = 'UPDATE_DETAILS';
export const UPDATE_INFO = 'UPDATE_INFO';
export const RESET_REPORT = 'RESET_REPORT';
